### ISSUE TITLE
Uncaught (in promise) SyntaxError: import not found: default in quill.js

### ISSUE THREAD

**Issue by QuentinAM** [lagden/svelte-editor-quill#1]
Hi i'm using your svelte editor like so in Typescript.

```ts
let EditorQuill: any;
onMount(async () => {
    const { Editor } = await import('@tadashi/svelte-editor-quill');
    EditorQuill = Editor;
});
...
<EditorQuill {options} on:text-change={...} data={...}/>
```

I had to add an `index.d.ts` with `declare module '@tadashi/svelte-editor-quill';` in the node_modules of your plugin.
It worked for like 30min but now i keep getting an error saying `Uncaught (in promise) SyntaxError: import not found: default` in `/node_modules/@tadashi/svelte-editor-quill/src/quill.js` line 1, i don't know if the error come cause of me, you or quill.

Do you have any advice on how to solve it ?
Thanks
Best regards

**Comment by djamadeus** [comment]
Same problem here when building with Vite...
`Uncaught SyntaxError: The requested module '/node_modules/quill/dist/quill.js?v=0c99661a' does not provide an export named 'default' (at quill.js:1:8)`

**Comment by lagden** [comment]
It looks like a (quill + sveltekit) issue!!
Change to the latest version 2.2.0
I fixed it.
