### ISSUE TITLE
How do you get the editor object in onTextChange event?

### ISSUE THREAD

**Issue by ferper04** [lagden/svelte-editor-quill#5]
Im trying to do this
`
quill.on('text-change', function (delta, old, source) {
  if (quill.getLength() > limit) {
    quill.deleteText(limit, quill.getLength());
  }
});`

**Comment by lagden** [comment]
It's is not possible to do that using this lib.
This event it is a `CustomEvent` fired by Quill `text-change` event.

https://github.com/lagden/svelte-editor-quill/blob/3.1.0/src/lib/quill.js#L25-L31
